name: Auto Update Sitemap

on:
  push:
    branches:
      - main
    paths:
      - '**.html'
      - '**/index.html'

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Sitemap with Last Modified Date
        run: |
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > sitemap.xml
          echo "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">" >> sitemap.xml
          
          find . -name "*.html" ! -name "google*.html" ! -name "404.html" | while read file; do
            url="https://politicalreport.netlify.app/${file#./}"
            lastmod=$(git log -1 --format="%ad" --date=short "$file" 2>/dev/null || date +%Y-%m-%d)

            echo "  <url>" >> sitemap.xml
            echo "    <loc>$url</loc>" >> sitemap.xml
            echo "    <lastmod>$lastmod</lastmod>" >> sitemap.xml
            echo "  </url>" >> sitemap.xml
          done

          echo "</urlset>" >> sitemap.xml

      - name: Commit and Push Sitemap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "🧭 Auto update sitemap with lastmod" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
